### ISSUE TITLE
Path to long 

### ISSUE THREAD

**Issue by aleanon** [radixdlt/radix-engine-toolkit#81]
When using the radix-engine-toolkit with Rust in Windows It's failing because of path to long:

path too long: 'C:/Users/myuser/.cargo/git/checkouts/radixdlt-scrypto-1833d92590086ce0/038ddee/transaction-scenarios/generated-examples/non_fungible_resource_with_remote_type/001--non-fungible-resource-with-remote-type-registration-8651ee2b9e026c5d9dded8b939b2087f59c0701dae3e3e13ed903edca71a9356.blob'; class=Filesystem (30)

Long-path doesn't work on win 11 so it's quite a hassle when you need to set up a different environment to use the library.

**Comment by 0xOmarA** [comment]
Hi @aleanon! I believe that this is an issue in Rust toolchain on Windows with the paths being too long. Historically, I've been able to resolve this issue through the fix [here](https://gist.github.com/leodutra/a25bc1f51e8779943df0a95d5a4839d1).

**Comment by 0xOmarA** [comment]
Will be closing this issue as it is stale and does not relate to RET.
